-- begin CLARIONSCHOOL_CLASSES
alter table CLARIONSCHOOL_CLASSES add constraint FK_CLARIONSCHOOL_CLASSES_ON_COURSE foreign key (COURSE_ID) references CLARIONSCHOOL_COURSES(ID)^
alter table CLARIONSCHOOL_CLASSES add constraint FK_CLARIONSCHOOL_CLASSES_ON_TEACHER_NUMBER foreign key (TEACHER_NUMBER) references CLARIONSCHOOL_TEACHERS(NUMBER_)^
create index IDX_CLARIONSCHOOL_CLASSES_ON_COURSE on CLARIONSCHOOL_CLASSES (COURSE_ID)^
create index IDX_CLARIONSCHOOL_CLASSES_ON_TEACHER_NUMBER on CLARIONSCHOOL_CLASSES (TEACHER_NUMBER)^
-- end CLARIONSCHOOL_CLASSES
-- begin CLARIONSCHOOL_STUDENTS
alter table CLARIONSCHOOL_STUDENTS add constraint FK_CLARIONSCHOOL_STUDENTS_ON_MAJOR foreign key (MAJOR_ID) references CLARIONSCHOOL_MAJORS(ID)^
create index IDX_CLARIONSCHOOL_STUDENTS_ON_MAJOR on CLARIONSCHOOL_STUDENTS (MAJOR_ID)^
-- end CLARIONSCHOOL_STUDENTS

-- begin CLARIONSCHOOL_ENROLLMENT
alter table CLARIONSCHOOL_ENROLLMENT add constraint FK_CLARIONSCHOOL_ENROLLMENT_ON_STUDENT_NUMBER foreign key (STUDENT_NUMBER) references CLARIONSCHOOL_STUDENTS(NUMBER_)^
alter table CLARIONSCHOOL_ENROLLMENT add constraint FK_CLARIONSCHOOL_ENROLLMENT_ON_CLASS_NUMBER foreign key (CLASS_NUMBER) references CLARIONSCHOOL_CLASSES(CLASS_NUMBER)^
create index IDX_CLARIONSCHOOL_ENROLLMENT_ON_STUDENT_NUMBER on CLARIONSCHOOL_ENROLLMENT (STUDENT_NUMBER)^
create index IDX_CLARIONSCHOOL_ENROLLMENT_ON_CLASS_NUMBER on CLARIONSCHOOL_ENROLLMENT (CLASS_NUMBER)^
-- end CLARIONSCHOOL_ENROLLMENT
-- begin CLARIONSCHOOL_TEACHERS
alter table CLARIONSCHOOL_TEACHERS add constraint FK_CLARIONSCHOOL_TEACHERS_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references CLARIONSCHOOL_MAJORS(ID)^
create index IDX_CLARIONSCHOOL_TEACHERS_ON_DEPARTMENT on CLARIONSCHOOL_TEACHERS (DEPARTMENT_ID)^
-- end CLARIONSCHOOL_TEACHERS
