alter table CLARIONSCHOOL_STUDENTS add constraint FK_CLARIONSCHOOL_STUDENTS_ON_MAJOR foreign key (MAJOR_ID) references CLARIONSCHOOL_MAJORS(ID);
create index IDX_CLARIONSCHOOL_STUDENTS_ON_MAJOR on CLARIONSCHOOL_STUDENTS (MAJOR_ID);
