create table CLARIONSCHOOL_ENROLLMENT (
    ID int generated by default as identity(start with 1) not null,
    --
    STUDENT_NUMBER varchar(10),
    CLASS_NUMBER varchar(10),
    MIDTERM_EXAM integer,
    FINAL_EXAM_COPY integer,
    TERM_PAPER integer,
    --
    primary key (ID)
);
