alter table CLARIONSCHOOL_CLASSES add constraint FK_CLARIONSCHOOL_CLASSES_ON_COURSE foreign key (COURSE_ID) references CLARIONSCHOOL_COURSES(ID);
create index IDX_CLARIONSCHOOL_CLASSES_ON_COURSE on CLARIONSCHOOL_CLASSES (COURSE_ID);
